apiVersion: v1
kind: Service
metadata:
  name: tomcat-nodeport
spec:
  selector:
    app: tom
  type: NodePort
  ports: 
  - name: tomcat
    protocol: TCP
    targetPort: 8080
    port: 8080
    nodePort: 30008
