apiVersion: v1
kind: Service
metadata:
  name: tomcat-nodeport
spec:
  selector:
    app: tomcat
  type: NodePort
  ports: 
    - name: tomcat
      protocol: TCP
      targetPort: 8080
      port: 8080

